### ISSUE TITLE
Cannot evaluate arithmetic inside of array index

### ISSUE THREAD

**Issue by maxenglander** [hashicorp/hil#28]
Trying to evaluate something like `${foo[2-1]}`, where `foo` is just an array with at least two members, fails with (formatting mine):

    Error: node doesn't support evaluation: *ast.Arithmetic{
        Op:2, Exprs:[]ast.Node{
            *ast.LiteralNode{
                Value:2,
                Typex:0x8,
                Posx:ast.Pos{Column:7, Line:1}
            },
            *ast.LiteralNode{
                Value:1, 
                Typex:0x8, 
                Posx:ast.Pos{Column:9, Line:1}
            }
        },
        Posx:ast.Pos{Column:7, Line:1}
    }

**Comment by mitchellh** [comment]
I have a fix queued up in #29
