### ISSUE TITLE
Escaped quotes not handled correctly by parser

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/hil#35]
In the new hand-written scanner/parser, the scanner is correctly handling escaped quotes in quoted sequences -- ensuring that they don't prematurely terminate the string token -- but the parser is missing the rule to replace an escaped quote with a literal quote.

This was reported in hashicorp/terraform#10236 .

**Comment by mitchellh** [comment]
Note that some BC here is to be expected due to this: https://github.com/hashicorp/hcl/pull/150

**Comment by apparentlymart** [comment]
Ahh... I had a feeling something had changed somewhere else that had made this behavior different, since I didn't recall seeing this escaped quote handling in the old parser. Glad to see that there's a corresponding HCL change that explains that. :grinning:
