### ISSUE TITLE
Missing unary plus and minus operators support

### ISSUE THREAD

**Issue by VladRassokhin** [hashicorp/hil#4]
They was introduced in Terraform 0.6.9, see [changelog](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#069-january-8-2016) and [pull-request](https://github.com/hashicorp/terraform/pull/3621).
But during migration to separate package/repository support was lost alongside with tests.
Recently @mitchellh added support for unary minus operator, but it would be nice to use original code.

Why this happened:
* `hashicorp/hel` (previous name) was branched on 05.12.2015.
* PR-3621 was merged into `hashicorp/terraform/config/lang` on 18.12.2015
* Terraform switched to `hashicorp/hil` on 03.02.2016. At this stage code in `hashicorp/terraform/config/lang` was dropped, without merging into `hashicorp/hil`)

**Comment by mitchellh** [comment]
I grabbed the unary tests and put them in and they all passed, so I believe this is fixed. See here:

https://github.com/hashicorp/hil/commit/ae9b5bd7eb9d52b58296a742da99d5feaaaccd46
