### ISSUE TITLE
Feature request: Trim mode

### ISSUE THREAD

**Issue by vancluever** [hashicorp/hil#47]
Consider the following block:

```
variable "one" {
  type    = "string"
  default = "one"
}

variable "two" {
  type    = "string"
  default = ""
}

variable "three" {
  type    = "string"
  default = "three"
}

output "output" {
  value = <<EOS
${var.one}
${var.two}
${var.three}
EOS
}
```

This gives:

```
one

three
```

What would be nice, is if we could do something like:

```
output "output" {
  value = <<EOS
${var.one}
${var.two -}
${var.three}
EOS
}
```

And get instead:

```
one
three
```

I'd love to do the work if someone tells me where to start.

I'm guessing it would be an extension to the scanner to locate `-}` (and maybe `${-` for good measure), adding a `TrimEnd` and maybe `TrimStart` to `hil.EvaluationResult`, and then writing the resulting code in Terraform to handle the trimming of the heredoc or "multiline" string (ie: trim whitespace to next non-whitespace character, or all previous whitespace back to and including last newline).

This is new territory for me, so my logic may be off. Again, would love to know where to look. :)

**Comment by mitchellh** [comment]
I'd actually prefer if this wasn't a language feature and instead was just done using `replace()` type functions. Sorry!

**Comment by vancluever** [comment]
@mitchellh that's too bad :( I think I'll be able to manage myself, but I think the config will be less semantic or readable if there was some sort of API to handle user-defined line trimming behaviour.

Also, something like `replace(data.template_file.template.rendered, /^\\s+$/, "")` may not catch everything when you are trying to make a template a bit more readable. 

Consider the above example with a bit more text:

```
output "output" {
  value = <<EOS
# Intentional Heading

${var.one}
${var.two}
${var.three}
EOS
}
```

Now all of a sudden, the `replace` function wipes out the intentional empty line too.

Further to that, the TF code to do this now needs to be piped thru a `template_file` data source, even though this would not have been needed in the first place if we had a built-in trim API.

As I'm typing this I'm thinking that there might be unforeseen gotchas in making this work in Terraform due to graph expansion issues and what not, but I still think that it would be a nice to have. Having the function in ERB for example goes a long way in making templates easier to read and work with, for me anyway.

I'm not too sure if there's something I'm missing here that would allow this to happen while maintaining readability - if there is, I'd appreciate the help!
