### ISSUE TITLE
Backslash escapes not working properly at the end of quoted strings

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/hil#48]
@ziggythehamster pointed out via Terraform's Gitter chat that there's still some quirkiness with backslash escapes in HIL.

Consider this example:

```hcl
resource "null_resource" "foo" {
  triggers = {
    thing = "${replace(var.thing, "\\", "/")}"
  }
}
```

This produces a syntax error in the HIL parser:

```
Error loading config: Error loading try.tf: Error reading config for null_resource[foo]: parse error at 1:31: expected "${" but found invalid sequence ")}"
```

It seems that the `\\"` sequence is escaping the quote, rather than escaping the backslash as expected. Adding a space before the quote mark seems to get past the parse error. Presumably this is a logic error in the escape handling.

**Comment by VladRassokhin** [comment]
Agree, though same result would be if you replace `\\` with `\`.

**Comment by VladRassokhin** [comment]
Actually problem is in HIL parser. HCL works fine.

**Comment by VladRassokhin** [comment]
Here's simple test. Just add this code after `eval_test.go:38` and run tests. (yep, it's copy-paste of `eval_test.go:21-38`)
```
		{
			Input:      `${"foo\\"}`,
			Scope:      nil,
			Result:     `foo\`,
			ResultType: TypeString,
		},
		{
			Input:      `${"foo\\\\"}`,
			Scope:      nil,
			Result:     `foo\\`,
			ResultType: TypeString,
		},
```

**Comment by eraserhd** [comment]
I just encountered this:
```
> "hello\nworld"
hello
world
> "\\n"
\n
> replace("hello\nworld","\n","\\n")
hello\nworld
> "hello\\world"
hello\world
> "hello\\\\world"
hello\\world
> replace("hello\\world","\\","\\\\")
parse error at 1:32: expected ")" but found invalid sequence "\\"
> "\\"
parse error at 1:4: expected "${" but found invalid sequence "\\\\\"}"
> "a\\b"
a\b
> "a\\"
parse error at 1:4: expected "${" but found invalid sequence "a\\\\\"}"
> "\\b"
\b
> "\\\\"
parse error at 1:4: expected "${" but found invalid sequence "\\\\\\\\\"}"
> "\\\\a"
\\a
> replace("\\a","a","")
\
>
```

**Comment by alkar** [comment]
Just encountered the same issue, in a template:

This produces `* data.template_file.t: data.template_file.t: failed to render : parse error at xx:yy: invalid backslash escape sequence`
```
${v ? "" : "\\" }
```

While the following works:
```
${v ? "" : "\\" }
```
as well as:
```
${v ? "" : "\n" }
```
